#!/usr/bin/env python3
"""Validate Tonight's Blueprint assets, without needing Unity.

Blueprints are ScriptableObject assets, so content errors that C# would have
caught at compile time now surface at runtime instead. Validation is the
replacement safety net, and it has two halves:

* **In-Editor** (``OnValidate`` plus ``Tonight > Blueprints > Validate All``)
  catches per-asset problems and shows them to the designer immediately.
* **This script**, run in CI, catches the **cross-asset** problems a single
  asset cannot see: duplicate identities, storm phase discontinuities, loot
  table reference cycles, incomplete per-material mesh coverage.

An asset can be individually valid and still wrong in the context of its peers.
Those are the failures this exists for.

Usage::

    python3 tools/validate_blueprints.py
    python3 tools/validate_blueprints.py --root unity/Tonight/Assets/Tonight/Blueprints
    python3 tools/validate_blueprints.py --strict    # warnings fail too
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

DEFAULT_ROOT = Path("unity/Tonight/Assets/Tonight/Blueprints")

# Unity's YAML dialect carries tags PyYAML cannot load (`!u!114 &11400000`) and
# a `%TAG` directive, so these assets are scanned with targeted regexes rather
# than a general parser. That is a deliberate trade: a full parse would need a
# dependency and a custom resolver to answer questions this shallow.
_FIELD_RE = re.compile(r"^\s{2}(\w+):\s*(.*)$")
_SCRIPT_GUID_RE = re.compile(r"m_Script:.*guid:\s*([0-9a-f]{32})")
_NAME_RE = re.compile(r"^\s*m_Name:\s*(.*)$", re.MULTILINE)
_GUID_REF_RE = re.compile(r"guid:\s*([0-9a-f]{32})")


class Severity:
    ERROR = "error"
    WARNING = "warning"


@dataclass
class Finding:
    severity: str
    message: str
    asset: str = ""

    def __str__(self) -> str:
        where = f"{self.asset}: " if self.asset else ""
        return f"[{self.severity}] {where}{self.message}"


@dataclass
class Asset:
    """A shallowly-parsed Blueprint asset."""

    path: Path
    name: str
    script_guid: str
    fields: dict[str, str] = field(default_factory=dict)
    referenced_guids: list[str] = field(default_factory=list)
    raw: str = ""

    @property
    def blueprint_id(self) -> str:
        return self.fields.get("_blueprintId", "").strip()

    def number(self, key: str) -> float | None:
        raw = self.fields.get(key)
        if raw is None:
            return None
        try:
            return float(raw)
        except ValueError:
            return None

    def integer(self, key: str) -> int | None:
        value = self.number(key)
        return None if value is None else int(value)

    def looks_like(self, *keys: str) -> bool:
        """Heuristic type test: does this asset carry these fields?

        Type is inferred from field presence rather than from the script GUID,
        because the GUIDs are generated by Unity and are not knowable here.
        """
        return all(key in self.fields for key in keys)


def parse_asset(path: Path) -> Asset | None:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError as error:
        print(f"Could not read {path}: {error}", file=sys.stderr)
        return None

    name_match = _NAME_RE.search(text)
    name = name_match.group(1).strip() if name_match else path.stem

    script_match = _SCRIPT_GUID_RE.search(text)
    script_guid = script_match.group(1) if script_match else ""

    fields: dict[str, str] = {}
    for line in text.splitlines():
        match = _FIELD_RE.match(line)
        if match:
            fields[match.group(1)] = match.group(2).strip()

    # Collect referenced GUIDs, excluding the m_Script line itself. Filtering by
    # VALUE (g != script_guid) would silently drop a legitimate reference that
    # happened to equal the script's GUID, so the line is removed instead.
    without_script = "\n".join(
        line for line in text.splitlines() if "m_Script:" not in line
    )
    referenced = _GUID_REF_RE.findall(without_script)

    return Asset(
        path=path,
        name=name or path.stem,
        script_guid=script_guid,
        fields=fields,
        referenced_guids=referenced,
        raw=text,
    )


def load_assets(root: Path) -> list[Asset]:
    assets: list[Asset] = []
    for path in sorted(root.rglob("*.asset")):
        parsed = parse_asset(path)
        if parsed is not None:
            assets.append(parsed)
    return assets


# --------------------------------------------------------------------------
# Cross-asset checks
# --------------------------------------------------------------------------


def check_unique_blueprint_ids(assets: list[Asset]) -> list[Finding]:
    """Two assets claiming one identity makes every reference to it ambiguous."""
    findings: list[Finding] = []
    by_id: dict[str, list[Asset]] = defaultdict(list)

    for asset in assets:
        if not asset.blueprint_id:
            # Only flag assets that look like Blueprints at all; a registry or
            # a Unity settings asset legitimately has no BlueprintId.
            if "_displayName" in asset.fields:
                findings.append(
                    Finding(
                        Severity.ERROR,
                        "BlueprintId is empty. Re-save the asset in the Editor to "
                        "generate one.",
                        asset.name,
                    )
                )
            continue
        by_id[asset.blueprint_id].append(asset)

    for blueprint_id, group in by_id.items():
        if len(group) > 1:
            names = ", ".join(a.name for a in group)
            findings.append(
                Finding(
                    Severity.ERROR,
                    f"BlueprintId {blueprint_id} is claimed by {len(group)} assets: "
                    f"{names}. Ids must be unique.",
                )
            )

    return findings


def check_rarity_tiers(assets: list[Asset]) -> list[Finding]:
    """Rarity tiers must be unique, or loot bias shifts land unpredictably."""
    findings: list[Finding] = []
    rarities = [a for a in assets if a.looks_like("_tier", "_damageMultiplier", "_lootWeight")]

    if not rarities:
        return findings

    by_tier: dict[int, list[str]] = defaultdict(list)
    for asset in rarities:
        tier = asset.integer("_tier")
        if tier is None:
            findings.append(Finding(Severity.ERROR, "Tier is not a number.", asset.name))
            continue
        by_tier[tier].append(asset.name)

    for tier, names in sorted(by_tier.items()):
        if len(names) > 1:
            findings.append(
                Finding(
                    Severity.ERROR,
                    f"Rarity tier {tier} is used by {len(names)} assets: "
                    f"{', '.join(names)}. Tiers must be unique.",
                )
            )

    tiers = sorted(by_tier)
    expected = list(range(len(tiers)))
    if tiers and tiers != expected:
        findings.append(
            Finding(
                Severity.WARNING,
                f"Rarity tiers are {tiers}, not contiguous from 0. A gap makes "
                "a loot table's RarityBias skip a tier.",
            )
        )

    return findings


def check_storm_phase_continuity(assets: list[Asset]) -> list[Finding]:
    """Each phase must start where the last one ended.

    A gap here is a circle that silently teleports mid-match, which no single
    asset can detect about itself.
    """
    findings: list[Finding] = []
    phases = [a for a in assets if a.looks_like("_phaseIndex", "_startRadius", "_endRadius")]

    if not phases:
        return findings

    ordered: list[tuple[int, Asset]] = []
    for asset in phases:
        index = asset.integer("_phaseIndex")
        if index is None:
            findings.append(Finding(Severity.ERROR, "PhaseIndex is not a number.", asset.name))
            continue
        ordered.append((index, asset))

    ordered.sort(key=lambda pair: pair[0])

    seen: set[int] = set()
    for index, asset in ordered:
        if index in seen:
            findings.append(
                Finding(Severity.ERROR, f"Duplicate PhaseIndex {index}.", asset.name)
            )
        seen.add(index)

    indices = [index for index, _ in ordered]
    if indices and indices != list(range(len(indices))):
        findings.append(
            Finding(
                Severity.WARNING,
                f"Storm phase indices are {indices}, not contiguous from 0.",
            )
        )

    for (prev_index, previous), (index, current) in zip(ordered, ordered[1:]):
        previous_end = previous.number("_endRadius")
        current_start = current.number("_startRadius")
        if previous_end is None or current_start is None:
            continue

        if abs(previous_end - current_start) > 0.01:
            findings.append(
                Finding(
                    Severity.ERROR,
                    f"Phase {index} starts at radius {current_start:g} m but phase "
                    f"{prev_index} ended at {previous_end:g} m. The circle would "
                    "teleport.",
                    current.name,
                )
            )

    total = 0.0
    for _, asset in ordered:
        wait = asset.number("_waitSeconds") or 0.0
        close = asset.number("_closeSeconds") or 0.0
        total += wait + close

    if total > 0:
        minutes = total / 60.0
        if not 12.0 <= minutes <= 22.0:
            findings.append(
                Finding(
                    Severity.WARNING,
                    f"Storm phases total {minutes:.1f} minutes. The design target "
                    "is a 16-18 minute match; over 22 is a tuning bug.",
                )
            )

    return findings


def check_loot_table_cycles(assets: list[Asset]) -> list[Finding]:
    """A loot table that reaches itself would recurse forever at spawn time."""
    findings: list[Finding] = []
    tables = [a for a in assets if a.looks_like("_entries", "_rollCount")]

    if not tables:
        return findings

    guid_by_path = {}
    for asset in tables:
        meta = asset.path.with_suffix(asset.path.suffix + ".meta")
        if not meta.exists():
            findings.append(
                Finding(
                    Severity.ERROR,
                    "Asset has no .meta file. A .meta is part of its asset; "
                    "without one Unity will generate a new GUID and every "
                    "reference to this table will break.",
                    asset.name,
                )
            )
            continue
        match = re.search(r"guid:\s*([0-9a-f]{32})", meta.read_text(encoding="utf-8"))
        if match:
            guid_by_path[match.group(1)] = asset

    # Edges: table -> referenced tables.
    edges: dict[str, set[str]] = defaultdict(set)

    for guid, asset in guid_by_path.items():
        for referenced in asset.referenced_guids:
            if referenced in guid_by_path:
                edges[guid].add(referenced)

    visiting: set[str] = set()
    visited: set[str] = set()

    def walk(node: str, trail: list[str]) -> None:
        if node in visiting:
            names = " -> ".join(guid_by_path[g].name for g in trail + [node])
            findings.append(
                Finding(Severity.ERROR, f"Loot table reference cycle: {names}.")
            )
            return
        if node in visited:
            return

        visiting.add(node)
        for neighbour in sorted(edges[node]):
            walk(neighbour, trail + [node])
        visiting.discard(node)
        visited.add(node)

    for guid in sorted(guid_by_path):
        walk(guid, [])

    return findings


def check_meta_files(assets: list[Asset], root: Path) -> list[Finding]:
    """Every asset needs its .meta, and every .meta needs its asset."""
    findings: list[Finding] = []

    for asset in assets:
        meta = asset.path.with_suffix(asset.path.suffix + ".meta")
        if not meta.exists():
            findings.append(
                Finding(Severity.ERROR, "Missing .meta file.", asset.name)
            )

    for meta in sorted(root.rglob("*.asset.meta")):
        target = meta.with_suffix("")
        if not target.exists():
            findings.append(
                Finding(
                    Severity.ERROR,
                    f"Orphaned .meta with no asset: {meta.name}",
                )
            )

    return findings


CHECKS = (
    ("unique blueprint ids", check_unique_blueprint_ids),
    ("rarity tiers", check_rarity_tiers),
    ("storm phase continuity", check_storm_phase_continuity),
    ("loot table cycles", check_loot_table_cycles),
)


def validate(root: Path) -> tuple[list[Finding], int]:
    """Run every check. Returns the findings and the asset count."""
    if not root.exists():
        return (
            [
                Finding(
                    Severity.WARNING,
                    f"Blueprint root {root} does not exist yet. Nothing to validate.",
                )
            ],
            0,
        )

    assets = load_assets(root)
    findings: list[Finding] = []

    for _, check in CHECKS:
        findings.extend(check(assets))

    findings.extend(check_meta_files(assets, root))

    if not assets:
        findings.append(
            Finding(
                Severity.WARNING,
                f"No Blueprint assets found under {root}. This is expected in "
                "pre-production; assets are authored in the Unity Editor "
                "(see docs/mcp/runbooks.md RB-01).",
            )
        )

    return findings, len(assets)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Treat warnings as failures.",
    )
    args = parser.parse_args(argv)

    findings, count = validate(args.root)

    errors = [f for f in findings if f.severity == Severity.ERROR]
    warnings = [f for f in findings if f.severity == Severity.WARNING]

    for finding in errors + warnings:
        stream = sys.stderr if finding.severity == Severity.ERROR else sys.stdout
        print(finding, file=stream)

    print(
        f"\nValidated {count} Blueprint asset(s): "
        f"{len(errors)} error(s), {len(warnings)} warning(s)."
    )

    if errors:
        return 1
    if warnings and args.strict:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
